---
abstract: 'A flood control (rate limiter) object'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-RateLimiter
requires:
  Class::Method::Modifiers: 0
  List::Objects::WithUtils: 2
  Object::ArrayType::New: 0.002
  namespace::clean: 0
resources:
  repository: git://github.com/avenj/object-ratelimiter.git
version: 1.001003
